const results = [
  {
    id: 227475,
    duration: 138,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/07/27/audio_5b7765f09f.mp3',
      waveformUrl: '/music/227475/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/07/27/08-22-32-31_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-227475.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.961907',
    href: '/music/upbeat-ethereal-horizons-227475/',
    alt: 'Background, Corporate, Ambient',
    title: null,
    description: 'Background, Corporate, Ambient, Minimalist, Inspire',
    name: 'Ethereal Horizons',
    tagLinks:
      '<a href="/music/search/background/">background</a> <a href="/music/search/corporate/">corporate</a>',
    likeCount: 127,
    likeHref: '/accounts/like/audio/227475/',
    commentCount: 1,
    commentHref: '/music/upbeat-ethereal-horizons-227475/#comments',
    contentIdCertificateUrl: '/music/227475/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/top-flow-28521292/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=227475">Sergio Prosvirini</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=227475">Pixabay</a>',
    vector: false,
    isEditorsChoice: false,
    isLowQuality: false,
    qualityStatus: 5,
    rating: 7.5,
    user: {
      id: 28521292,
      username: 'Top-Flow',
      firstName: 'Sergio',
      lastName: 'Prosvirini',
      avatarSrc:
        'https://cdn.pixabay.com/user/2023/12/27/08-39-22-829_96x96.jpg',
      profileUrl: '/users/top-flow-28521292/',
      socialLinks: [
        {
          url: 'https://topaudio.io',
          type: 5,
        },
      ],
      donation: {
        paypal: 'https://www.buymeacoffee.com/topflow',
        method: 1,
      },
      donations: ['https://www.buymeacoffee.com/topflow'],
      followerCount: 3088,
      aboutMe:
        'Our platform, created by two visionary musicians, is the go-to destination for bloggers and content creators looking for premium tracks.\r\nTrusted by industry giants like Coca-Cola and Samsung, "Top-Audio" is the go-to platform for captivating and memorable music that leaves a lasting impact.\r\nJoin the league of successful bloggers and content creators who have chosen "Top-Audio" to enhance their projects with the same music trusted by global titans.',
      isAvailableForHire: true,
      isActive: true,
    },
    viewCount: 11830,
    downloadCount: 286,
  },
  {
    id: 227974,
    duration: 98,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/07/29/audio_4e09b35d5b.mp3',
      waveformUrl: '/music/227974/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/07/29/14-29-04-540_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-227974.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.962877',
    href: '/music/dance-letx27s-meet-michelle-synthpop-version-background-music-for-video-227974/',
    alt: 'Background, Background Music',
    title: null,
    description: 'Background, Background Music, Synthpop Music',
    name: "Let's meet Michelle. Synthpop version Background music for video",
    tagLinks: '<a href="/music/search/background/">background</a>',
    likeCount: 105,
    likeHref: '/accounts/like/audio/227974/',
    commentCount: 1,
    commentHref:
      '/music/dance-letx27s-meet-michelle-synthpop-version-background-music-for-video-227974/#comments',
    contentIdCertificateUrl: '/music/227974/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/white_records-32584949/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=227974">Maksym Dudchyk</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=227974">Pixabay</a>',
    vector: false,
    isEditorsChoice: false,
    isLowQuality: true,
    qualityStatus: 5,
    rating: 7,
    user: {
      id: 32584949,
      username: 'White_Records',
      firstName: 'Maksym',
      lastName: 'Dudchyk',
      avatarSrc:
        'https://cdn.pixabay.com/user/2023/07/22/15-50-31-85_96x96.png',
      profileUrl: '/users/white_records-32584949/',
      socialLinks: [
        {
          url: 'https://facebook.com/profile.php?id=100038573046142',
          type: 0,
        },
        {
          url: 'https://instagram.com/white_recordsmd/',
          type: 2,
        },
        {
          url: 'https://soundcloud.com/whiterecords1',
          type: 3,
        },
        {
          url: 'https://youtube.com/channel/UCi5cB6kg5ZDNtZQ8SawRUvg',
          type: 4,
        },
        {
          url: 'https://buymeacoffee.com/dmdproduction/extras',
          type: 5,
        },
      ],
      donation: {
        paypal: 'https://buymeacoffee.com/dmdproduction',
        method: 1,
      },
      donations: ['https://buymeacoffee.com/dmdproduction'],
      followerCount: 1588,
      aboutMe:
        '📌 Music licenses https://bit.ly/3w9Qy6k\r\nSupport with a donation 💜 https://www.buymeacoffee.com/dmdproduction\r\n📌 My PayPal dmdproductiondmd@gmail.com\r\nHere, we will be publishing instrumental beats and other music for your listening pleasure. Our channel is dedicated to providing you with high-quality, original content that is perfect for studying, working, relaxing, or just vibing out.',
      isAvailableForHire: false,
      isActive: true,
    },
    viewCount: 3420,
    downloadCount: 35,
  },
  {
    id: 227969,
    duration: 31,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/07/29/audio_111d75ef40.mp3',
      waveformUrl: '/music/227969/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/07/29/14-18-31-201_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-227969.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.963572',
    href: '/music/dance-letx27s-meet-michelle-synthpop-background-music-for-video-30s-227969/',
    alt: 'Background, Background Music',
    title: null,
    description: 'Background, Background Music, Music For Video',
    name: "Let's meet Michelle Synthpop Background music for video 30s",
    tagLinks: '<a href="/music/search/background/">background</a>',
    likeCount: 101,
    likeHref: '/accounts/like/audio/227969/',
    commentCount: 1,
    commentHref:
      '/music/dance-letx27s-meet-michelle-synthpop-background-music-for-video-30s-227969/#comments',
    contentIdCertificateUrl: '/music/227969/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/white_records-32584949/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=227969">Maksym Dudchyk</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=227969">Pixabay</a>',
    vector: false,
    isEditorsChoice: false,
    isLowQuality: true,
    qualityStatus: 5,
    rating: 7,
    user: {
      id: 32584949,
      username: 'White_Records',
      firstName: 'Maksym',
      lastName: 'Dudchyk',
      avatarSrc:
        'https://cdn.pixabay.com/user/2023/07/22/15-50-31-85_96x96.png',
      profileUrl: '/users/white_records-32584949/',
      socialLinks: [
        {
          url: 'https://facebook.com/profile.php?id=100038573046142',
          type: 0,
        },
        {
          url: 'https://instagram.com/white_recordsmd/',
          type: 2,
        },
        {
          url: 'https://soundcloud.com/whiterecords1',
          type: 3,
        },
        {
          url: 'https://youtube.com/channel/UCi5cB6kg5ZDNtZQ8SawRUvg',
          type: 4,
        },
        {
          url: 'https://buymeacoffee.com/dmdproduction/extras',
          type: 5,
        },
      ],
      donation: {
        paypal: 'https://buymeacoffee.com/dmdproduction',
        method: 1,
      },
      donations: ['https://buymeacoffee.com/dmdproduction'],
      followerCount: 1588,
      aboutMe:
        '📌 Music licenses https://bit.ly/3w9Qy6k\r\nSupport with a donation 💜 https://www.buymeacoffee.com/dmdproduction\r\n📌 My PayPal dmdproductiondmd@gmail.com\r\nHere, we will be publishing instrumental beats and other music for your listening pleasure. Our channel is dedicated to providing you with high-quality, original content that is perfect for studying, working, relaxing, or just vibing out.',
      isAvailableForHire: false,
      isActive: true,
    },
    viewCount: 402,
    downloadCount: 17,
  },
  {
    id: 227971,
    duration: 39,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/07/29/audio_a3b429be72.mp3',
      waveformUrl: '/music/227971/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/07/29/14-18-22-823_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-227971.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.964216',
    href: '/music/dance-letx27s-meet-michelle-synthpop-background-music-for-video-40s-227971/',
    alt: 'Background, Background Music',
    title: null,
    description: 'Background, Background Music, Synthpop Music, Pop Music',
    name: "Let's meet Michelle Synthpop Background music for video 40s",
    tagLinks: '<a href="/music/search/background/">background</a>',
    likeCount: 100,
    likeHref: '/accounts/like/audio/227971/',
    commentCount: 1,
    commentHref:
      '/music/dance-letx27s-meet-michelle-synthpop-background-music-for-video-40s-227971/#comments',
    contentIdCertificateUrl: '/music/227971/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/white_records-32584949/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=227971">Maksym Dudchyk</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=227971">Pixabay</a>',
    vector: false,
    isEditorsChoice: false,
    isLowQuality: true,
    qualityStatus: 5,
    rating: 7,
    user: {
      id: 32584949,
      username: 'White_Records',
      firstName: 'Maksym',
      lastName: 'Dudchyk',
      avatarSrc:
        'https://cdn.pixabay.com/user/2023/07/22/15-50-31-85_96x96.png',
      profileUrl: '/users/white_records-32584949/',
      socialLinks: [
        {
          url: 'https://facebook.com/profile.php?id=100038573046142',
          type: 0,
        },
        {
          url: 'https://instagram.com/white_recordsmd/',
          type: 2,
        },
        {
          url: 'https://soundcloud.com/whiterecords1',
          type: 3,
        },
        {
          url: 'https://youtube.com/channel/UCi5cB6kg5ZDNtZQ8SawRUvg',
          type: 4,
        },
        {
          url: 'https://buymeacoffee.com/dmdproduction/extras',
          type: 5,
        },
      ],
      donation: {
        paypal: 'https://buymeacoffee.com/dmdproduction',
        method: 1,
      },
      donations: ['https://buymeacoffee.com/dmdproduction'],
      followerCount: 1588,
      aboutMe:
        '📌 Music licenses https://bit.ly/3w9Qy6k\r\nSupport with a donation 💜 https://www.buymeacoffee.com/dmdproduction\r\n📌 My PayPal dmdproductiondmd@gmail.com\r\nHere, we will be publishing instrumental beats and other music for your listening pleasure. Our channel is dedicated to providing you with high-quality, original content that is perfect for studying, working, relaxing, or just vibing out.',
      isAvailableForHire: false,
      isActive: true,
    },
    viewCount: 1992,
    downloadCount: 21,
  },
  {
    id: 227972,
    duration: 54,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/07/29/audio_5567cbdd68.mp3',
      waveformUrl: '/music/227972/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/07/29/14-18-22-22_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-227972.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.964927',
    href: '/music/dance-letx27s-meet-michelle-synthpop-background-music-for-video-60s-227972/',
    alt: 'Background, Background Music',
    title: null,
    description: 'Background, Background Music, Synthpop Music',
    name: "Let's meet Michelle Synthpop Background music for video 60s",
    tagLinks: '<a href="/music/search/background/">background</a>',
    likeCount: 100,
    likeHref: '/accounts/like/audio/227972/',
    commentCount: 1,
    commentHref:
      '/music/dance-letx27s-meet-michelle-synthpop-background-music-for-video-60s-227972/#comments',
    contentIdCertificateUrl: '/music/227972/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/white_records-32584949/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=227972">Maksym Dudchyk</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=227972">Pixabay</a>',
    vector: false,
    isEditorsChoice: false,
    isLowQuality: true,
    qualityStatus: 5,
    rating: 7,
    user: {
      id: 32584949,
      username: 'White_Records',
      firstName: 'Maksym',
      lastName: 'Dudchyk',
      avatarSrc:
        'https://cdn.pixabay.com/user/2023/07/22/15-50-31-85_96x96.png',
      profileUrl: '/users/white_records-32584949/',
      socialLinks: [
        {
          url: 'https://facebook.com/profile.php?id=100038573046142',
          type: 0,
        },
        {
          url: 'https://instagram.com/white_recordsmd/',
          type: 2,
        },
        {
          url: 'https://soundcloud.com/whiterecords1',
          type: 3,
        },
        {
          url: 'https://youtube.com/channel/UCi5cB6kg5ZDNtZQ8SawRUvg',
          type: 4,
        },
        {
          url: 'https://buymeacoffee.com/dmdproduction/extras',
          type: 5,
        },
      ],
      donation: {
        paypal: 'https://buymeacoffee.com/dmdproduction',
        method: 1,
      },
      donations: ['https://buymeacoffee.com/dmdproduction'],
      followerCount: 1588,
      aboutMe:
        '📌 Music licenses https://bit.ly/3w9Qy6k\r\nSupport with a donation 💜 https://www.buymeacoffee.com/dmdproduction\r\n📌 My PayPal dmdproductiondmd@gmail.com\r\nHere, we will be publishing instrumental beats and other music for your listening pleasure. Our channel is dedicated to providing you with high-quality, original content that is perfect for studying, working, relaxing, or just vibing out.',
      isAvailableForHire: false,
      isActive: true,
    },
    viewCount: 4575,
    downloadCount: 36,
  },
  {
    id: 227970,
    duration: 38,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/07/29/audio_2a8fa381af.mp3',
      waveformUrl: '/music/227970/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/07/29/14-24-21-191_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-227970.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.965594',
    href: '/music/dance-letx27s-meet-michelle-synthpop-background-music-for-video-38s-227970/',
    alt: 'Background, Background Music',
    title: null,
    description: 'Background, Background Music, Music For Video',
    name: "Let's meet Michelle Synthpop Background music for video 38s",
    tagLinks: '<a href="/music/search/background/">background</a>',
    likeCount: 100,
    likeHref: '/accounts/like/audio/227970/',
    commentCount: 1,
    commentHref:
      '/music/dance-letx27s-meet-michelle-synthpop-background-music-for-video-38s-227970/#comments',
    contentIdCertificateUrl: '/music/227970/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/white_records-32584949/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=227970">Maksym Dudchyk</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=227970">Pixabay</a>',
    vector: false,
    isEditorsChoice: false,
    isLowQuality: true,
    qualityStatus: 5,
    rating: 7,
    user: {
      id: 32584949,
      username: 'White_Records',
      firstName: 'Maksym',
      lastName: 'Dudchyk',
      avatarSrc:
        'https://cdn.pixabay.com/user/2023/07/22/15-50-31-85_96x96.png',
      profileUrl: '/users/white_records-32584949/',
      socialLinks: [
        {
          url: 'https://facebook.com/profile.php?id=100038573046142',
          type: 0,
        },
        {
          url: 'https://instagram.com/white_recordsmd/',
          type: 2,
        },
        {
          url: 'https://soundcloud.com/whiterecords1',
          type: 3,
        },
        {
          url: 'https://youtube.com/channel/UCi5cB6kg5ZDNtZQ8SawRUvg',
          type: 4,
        },
        {
          url: 'https://buymeacoffee.com/dmdproduction/extras',
          type: 5,
        },
      ],
      donation: {
        paypal: 'https://buymeacoffee.com/dmdproduction',
        method: 1,
      },
      donations: ['https://buymeacoffee.com/dmdproduction'],
      followerCount: 1588,
      aboutMe:
        '📌 Music licenses https://bit.ly/3w9Qy6k\r\nSupport with a donation 💜 https://www.buymeacoffee.com/dmdproduction\r\n📌 My PayPal dmdproductiondmd@gmail.com\r\nHere, we will be publishing instrumental beats and other music for your listening pleasure. Our channel is dedicated to providing you with high-quality, original content that is perfect for studying, working, relaxing, or just vibing out.',
      isAvailableForHire: false,
      isActive: true,
    },
    viewCount: 432,
    downloadCount: 11,
  },
  {
    id: 219592,
    duration: 118,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/06/25/audio_7bfb8d2ab0.mp3',
      waveformUrl: '/music/219592/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/06/25/10-06-34-296_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-219592.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.966281',
    href: '/music/future-bass-in-slow-motion-inspiring-ambient-lounge-219592/',
    alt: 'Future Bass, Abstract, Fashion, Action',
    title: null,
    description: 'Future Bass, Abstract, Fashion, Action, Advertising, Ambient',
    name: 'In Slow Motion (Inspiring Ambient Lounge)',
    tagLinks:
      '<a href="/music/search/future%20bass/">future bass</a> <a href="/music/search/abstract/">abstract</a>',
    likeCount: 763,
    likeHref: '/accounts/like/audio/219592/',
    commentCount: 10,
    commentHref:
      '/music/future-bass-in-slow-motion-inspiring-ambient-lounge-219592/#comments',
    contentIdCertificateUrl: '/music/219592/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/soundbay-601514/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=219592">soundbay</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=219592">Pixabay</a>',
    vector: false,
    isEditorsChoice: true,
    isLowQuality: false,
    qualityStatus: 5,
    rating: 8.5,
    user: {
      id: 601514,
      username: 'soundbay',
      firstName: '',
      lastName: '',
      avatarSrc:
        'https://cdn.pixabay.com/user/2023/04/11/06-38-27-969_96x96.jpg',
      profileUrl: '/users/soundbay-601514/',
      socialLinks: [
        {
          url: 'https://soundcloud.com/sbrfm',
          type: 3,
        },
        {
          url: 'https://youtube.com/@soundbay_RFM',
          type: 4,
        },
        {
          url: 'https://soundbay.org',
          type: 5,
        },
      ],
      donation: {
        paypal: 'https://buymeacoffee.com/soundbay',
        method: 1,
      },
      donations: ['https://buymeacoffee.com/soundbay'],
      followerCount: 292,
      aboutMe:
        'MORE MUSIC:\r\n\r\nWeb-site: soundbay.org\r\nYouTube: https://www.youtube.com/@soundbay_rfm\r\nSoundcloud: soundcloud.com/sbrfm\r\nSpotify: spoti.fi/3zeNsiL\r\nApple Music: apple.co/3XGY1VN\r\n\r\nsoundbay is a sound production studio specializing on composing music for movie production, tv, advertising, you-tube videos, corporate projects and video-game development. Visit our web-site!',
      isAvailableForHire: true,
      isActive: true,
    },
    viewCount: 530828,
    downloadCount: 5174,
  },
  {
    id: 223627,
    duration: 106,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/07/11/audio_8729e92325.mp3',
      waveformUrl: '/music/223627/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/07/11/06-48-54-401_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-223627.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.967125',
    href: '/music/upbeat-endless-horizons-223627/',
    alt: 'Summer, Tropical, Happy, Travel, Family',
    title: null,
    description: 'Summer, Tropical, Happy, Travel, Family, Pop, Vacation',
    name: 'Endless Horizons',
    tagLinks:
      '<a href="/music/search/summer/">summer</a> <a href="/music/search/tropical/">tropical</a> <a href="/music/search/happy/">happy</a>',
    likeCount: 529,
    likeHref: '/accounts/like/audio/223627/',
    commentCount: 3,
    commentHref: '/music/upbeat-endless-horizons-223627/#comments',
    contentIdCertificateUrl: '/music/223627/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/top-flow-28521292/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=223627">Sergio Prosvirini</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=223627">Pixabay</a>',
    vector: false,
    isEditorsChoice: false,
    isLowQuality: false,
    qualityStatus: 5,
    rating: 7.5,
    user: {
      id: 28521292,
      username: 'Top-Flow',
      firstName: 'Sergio',
      lastName: 'Prosvirini',
      avatarSrc:
        'https://cdn.pixabay.com/user/2023/12/27/08-39-22-829_96x96.jpg',
      profileUrl: '/users/top-flow-28521292/',
      socialLinks: [
        {
          url: 'https://topaudio.io',
          type: 5,
        },
      ],
      donation: {
        paypal: 'https://www.buymeacoffee.com/topflow',
        method: 1,
      },
      donations: ['https://www.buymeacoffee.com/topflow'],
      followerCount: 3088,
      aboutMe:
        'Our platform, created by two visionary musicians, is the go-to destination for bloggers and content creators looking for premium tracks.\r\nTrusted by industry giants like Coca-Cola and Samsung, "Top-Audio" is the go-to platform for captivating and memorable music that leaves a lasting impact.\r\nJoin the league of successful bloggers and content creators who have chosen "Top-Audio" to enhance their projects with the same music trusted by global titans.',
      isAvailableForHire: true,
      isActive: true,
    },
    viewCount: 83547,
    downloadCount: 812,
  },
  {
    id: 226857,
    duration: 115,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/07/24/audio_5ec636ca14.mp3',
      waveformUrl: '/music/226857/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/07/26/00-05-51-743_200x200.png',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-226857.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.967772',
    href: '/music/bije-night-detective-226857/',
    alt: 'Beat, Electronic, Dreamy',
    title: null,
    description: 'Beat, Electronic, Dreamy',
    name: 'Night Detective',
    tagLinks:
      '<a href="/music/search/beat/">beat</a> <a href="/music/search/electronic/">electronic</a> <a href="/music/search/dreamy/">dreamy</a>',
    likeCount: 110,
    likeHref: '/accounts/like/audio/226857/',
    commentCount: 3,
    commentHref: '/music/bije-night-detective-226857/#comments',
    contentIdCertificateUrl: '/music/226857/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/amaksi-28332361/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=226857">Amaksi</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=226857">Pixabay</a>',
    vector: false,
    isEditorsChoice: true,
    isLowQuality: false,
    qualityStatus: 5,
    rating: 8.5,
    user: {
      id: 28332361,
      username: 'Amaksi',
      firstName: '',
      lastName: '',
      avatarSrc:
        'https://cdn.pixabay.com/user/2023/06/08/13-51-27-627_96x96.jpg',
      profileUrl: '/users/amaksi-28332361/',
      socialLinks: [
        {
          url: 'https://open.spotify.com/artist/4tJmkO8z32dON6KheYsd8x',
          type: 6,
        },
      ],
      donation: {
        paypal: 'https://buymeacoffee.com/crownflyx',
        method: 1,
      },
      donations: [
        'https://buymeacoffee.com/crownflyx',
        'https://donationalerts.com/r/amaksi',
      ],
      followerCount: 288,
      aboutMe: '',
      isAvailableForHire: false,
      isActive: true,
    },
    viewCount: 72236,
    downloadCount: 775,
  },
  {
    id: 202298,
    duration: 133,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/04/14/audio_5d6668b1f0.mp3',
      waveformUrl: '/music/202298/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/04/14/22-20-51-951_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-202298.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: false,
    uploadDate: '2024-08-01T17:26:10.968407',
    href: '/music/beats-for-her-chill-upbeat-summel-travel-vlog-and-ig-music-royalty-free-use-202298/',
    alt: 'Travel Vlog, Vlog Music, Female Vocals',
    title: null,
    description: 'Travel Vlog, Vlog Music, Female Vocals, Summer House',
    name: 'For Her Chill Upbeat Summel Travel Vlog and IG Music Royalty Free Use',
    tagLinks:
      '<a href="/music/search/travel%20vlog/">travel vlog</a> <a href="/music/search/vlog%20music/">vlog music</a>',
    likeCount: 1795,
    likeHref: '/accounts/like/audio/202298/',
    commentCount: 28,
    commentHref:
      '/music/beats-for-her-chill-upbeat-summel-travel-vlog-and-ig-music-royalty-free-use-202298/#comments',
    contentIdCertificateUrl: null,
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/lidérc-34910776/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=202298">Lidérc</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=202298">Pixabay</a>',
    vector: false,
    isEditorsChoice: true,
    isLowQuality: false,
    qualityStatus: 5,
    rating: 8.5,
    user: {
      id: 34910776,
      username: 'Lidérc',
      firstName: 'Lidérc',
      lastName: '',
      avatarSrc:
        'https://cdn.pixabay.com/user/2023/08/28/23-59-30-895_96x96.jpg',
      profileUrl: '/users/lidérc-34910776/',
      socialLinks: [
        {
          url: 'https://soundcloud.com/lidercbeats',
          type: 3,
        },
        {
          url: 'https://youtube.com/channel/UCFD7LZhGf2q4j9Ka5WIAkUA',
          type: 4,
        },
      ],
      donation: {
        paypal: 'https://ko-fi.com/lmusic',
        method: 1,
      },
      donations: ['https://ko-fi.com/lmusic'],
      followerCount: 296,
      aboutMe:
        "The Wind, rain,  bells, chords, strings and more-  be inspired by sounds. It's more than just ♩♩ music, it defines you.",
      isAvailableForHire: false,
      isActive: true,
    },
    viewCount: 1896865,
    downloadCount: 11533,
  },
  {
    id: 217007,
    duration: 254,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/06/14/audio_0e2636099d.mp3',
      waveformUrl: '/music/217007/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/06/17/18-00-00-760_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-217007.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: false,
    uploadDate: '2024-08-01T17:26:10.969073',
    href: '/music/future-bass-amalgam-217007/',
    alt: 'Amalgam, Electronic, Orchestral, House',
    title: null,
    description: 'Amalgam, Electronic, Orchestral, House, Fusion, Mix, Modern',
    name: 'AMALGAM',
    tagLinks:
      '<a href="/music/search/amalgam/">amalgam</a> <a href="/music/search/electronic/">electronic</a>',
    likeCount: 596,
    likeHref: '/accounts/like/audio/217007/',
    commentCount: 9,
    commentHref: '/music/future-bass-amalgam-217007/#comments',
    contentIdCertificateUrl: null,
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/rockot-1947599/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=217007">Rockot</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=217007">Pixabay</a>',
    vector: false,
    isEditorsChoice: true,
    isLowQuality: false,
    qualityStatus: 5,
    rating: 9,
    user: {
      id: 1947599,
      username: 'Rockot',
      firstName: 'Rockot',
      lastName: '',
      avatarSrc:
        'https://cdn.pixabay.com/user/2023/10/24/14-21-56-296_96x96.jpeg',
      profileUrl: '/users/rockot-1947599/',
      socialLinks: [
        {
          url: 'https://www.facebook.com/ZakharDziubenko/',
          type: 0,
        },
        {
          url: 'https://www.instagram.com/zakhar_dziubenko/',
          type: 2,
        },
        {
          url: 'https://soundcloud.com/rockot_music',
          type: 3,
        },
        {
          url: 'https://www.youtube.com/@Rockot',
          type: 4,
        },
        {
          url: 'https://linktr.ee/rockot',
          type: 5,
        },
      ],
      donation: {
        paypal: 'https://www.buymeacoffee.com/rockot',
        method: 1,
      },
      donations: ['https://www.buymeacoffee.com/rockot'],
      followerCount: 769,
      aboutMe:
        'ROCKOT: Multi - genre music producer from Ukraine.\r\nYouTube: @Rockot\r\n\r\nMusic is free for non-commercial use only, if you want to use my music for any commercial purposes, write to me.\r\n\r\nSpotify: https://open.spotify.com/artist/1BsdkLD0LUxVTyWA9cgESJ?si=QDaau4sERk674BISPpzFNA\r\n\r\nLicense:https://audiojungle.net/user/beatroofstudio/portfolio\r\n\r\n\r\nThank you!',
      isAvailableForHire: true,
      isActive: true,
    },
    viewCount: 559132,
    downloadCount: 3756,
  },
  {
    id: 222444,
    duration: 160,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/07/06/audio_52c3ae306a.mp3',
      waveformUrl: '/music/222444/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/07/06/07-03-08-807_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-222444.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: false,
    uploadDate: '2024-08-01T17:26:10.969723',
    href: '/music/acoustic-group-sweet-serenade-222444/',
    alt: 'Romantic, Acoustic, Love, Song',
    title: null,
    description: 'Romantic, Acoustic, Love, Song, Instrumental, Slideshow',
    name: 'Sweet Serenade',
    tagLinks:
      '<a href="/music/search/romantic/">romantic</a> <a href="/music/search/acoustic/">acoustic</a> <a href="/music/search/love/">love</a>',
    likeCount: 517,
    likeHref: '/accounts/like/audio/222444/',
    commentCount: 0,
    commentHref: '/music/acoustic-group-sweet-serenade-222444/#comments',
    contentIdCertificateUrl: null,
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/neura-flow-43255620/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=222444">Umasha Pros</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=222444">Pixabay</a>',
    vector: false,
    isEditorsChoice: false,
    isLowQuality: true,
    qualityStatus: 5,
    rating: 7,
    user: {
      id: 43255620,
      username: 'Neura-Flow',
      firstName: 'Umasha',
      lastName: 'Pros',
      avatarSrc:
        'https://cdn.pixabay.com/user/2024/04/06/07-24-49-756_96x96.jpg',
      profileUrl: '/users/neura-flow-43255620/',
      socialLinks: [
        {
          url: 'https://soundcloud.com/umasha-prosvirina',
          type: 3,
        },
      ],
      donation: {
        paypal: 'https://buymeacoffee.com/topflow',
        method: 1,
      },
      donations: ['https://buymeacoffee.com/topflow'],
      followerCount: 728,
      aboutMe:
        'Neura Flow - is your ultimate destination for the finest and trendiest music crafted for bloggers and content creators. With a rich legacy of 15 years in the music industry, our musician brings you an exclusive collection that resonates with your creative vision.',
      isAvailableForHire: false,
      isActive: true,
    },
    viewCount: 87361,
    downloadCount: 693,
  },
  {
    id: 216049,
    duration: 144,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/06/10/audio_8045338a6f.mp3',
      waveformUrl: '/music/216049/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/06/10/06-30-52-461_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-216049.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.970354',
    href: '/music/corporate-lotus-sky-dreams-216049/',
    alt: 'Asian, Trip, Pop, Future, Uplifting',
    title: null,
    description: 'Asian, Trip, Pop, Future, Uplifting, Electronic, Dance',
    name: 'Lotus Sky Dreams',
    tagLinks:
      '<a href="/music/search/asian/">asian</a> <a href="/music/search/trip/">trip</a> <a href="/music/search/pop/">pop</a> <a href="/music/search/future/">future</a>',
    likeCount: 991,
    likeHref: '/accounts/like/audio/216049/',
    commentCount: 3,
    commentHref: '/music/corporate-lotus-sky-dreams-216049/#comments',
    contentIdCertificateUrl: '/music/216049/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/top-flow-28521292/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=216049">Sergio Prosvirini</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=216049">Pixabay</a>',
    vector: false,
    isEditorsChoice: false,
    isLowQuality: false,
    qualityStatus: 5,
    rating: 7.5,
    user: {
      id: 28521292,
      username: 'Top-Flow',
      firstName: 'Sergio',
      lastName: 'Prosvirini',
      avatarSrc:
        'https://cdn.pixabay.com/user/2023/12/27/08-39-22-829_96x96.jpg',
      profileUrl: '/users/top-flow-28521292/',
      socialLinks: [
        {
          url: 'https://topaudio.io',
          type: 5,
        },
      ],
      donation: {
        paypal: 'https://www.buymeacoffee.com/topflow',
        method: 1,
      },
      donations: ['https://www.buymeacoffee.com/topflow'],
      followerCount: 3088,
      aboutMe:
        'Our platform, created by two visionary musicians, is the go-to destination for bloggers and content creators looking for premium tracks.\r\nTrusted by industry giants like Coca-Cola and Samsung, "Top-Audio" is the go-to platform for captivating and memorable music that leaves a lasting impact.\r\nJoin the league of successful bloggers and content creators who have chosen "Top-Audio" to enhance their projects with the same music trusted by global titans.',
      isAvailableForHire: true,
      isActive: true,
    },
    viewCount: 186709,
    downloadCount: 1971,
  },
  {
    id: 214305,
    duration: 90,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/06/03/audio_b7b75975b8.mp3',
      waveformUrl: '/music/214305/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/06/03/12-21-43-432_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-214305.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.971031',
    href: '/music/dance-island-breeze-214305/',
    alt: 'Summer, Pop, Guitar, Tropical, Future',
    title: null,
    description: 'Summer, Pop, Guitar, Tropical, Future, Upbeat, Catchy',
    name: 'Island Breeze',
    tagLinks:
      '<a href="/music/search/summer/">summer</a> <a href="/music/search/pop/">pop</a> <a href="/music/search/guitar/">guitar</a>',
    likeCount: 1136,
    likeHref: '/accounts/like/audio/214305/',
    commentCount: 1,
    commentHref: '/music/dance-island-breeze-214305/#comments',
    contentIdCertificateUrl: '/music/214305/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/top-flow-28521292/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=214305">Sergio Prosvirini</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=214305">Pixabay</a>',
    vector: false,
    isEditorsChoice: false,
    isLowQuality: false,
    qualityStatus: 5,
    rating: 7.5,
    user: {
      id: 28521292,
      username: 'Top-Flow',
      firstName: 'Sergio',
      lastName: 'Prosvirini',
      avatarSrc:
        'https://cdn.pixabay.com/user/2023/12/27/08-39-22-829_96x96.jpg',
      profileUrl: '/users/top-flow-28521292/',
      socialLinks: [
        {
          url: 'https://topaudio.io',
          type: 5,
        },
      ],
      donation: {
        paypal: 'https://www.buymeacoffee.com/topflow',
        method: 1,
      },
      donations: ['https://www.buymeacoffee.com/topflow'],
      followerCount: 3088,
      aboutMe:
        'Our platform, created by two visionary musicians, is the go-to destination for bloggers and content creators looking for premium tracks.\r\nTrusted by industry giants like Coca-Cola and Samsung, "Top-Audio" is the go-to platform for captivating and memorable music that leaves a lasting impact.\r\nJoin the league of successful bloggers and content creators who have chosen "Top-Audio" to enhance their projects with the same music trusted by global titans.',
      isAvailableForHire: true,
      isActive: true,
    },
    viewCount: 193427,
    downloadCount: 1862,
  },
  {
    id: 228100,
    duration: 141,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/07/30/audio_09a1a55404.mp3',
      waveformUrl: '/music/228100/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/07/30/00-45-40-450_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-228100.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.971676',
    href: '/music/budouci-basy-nightfall-future-bass-music-228100/',
    alt: 'Future Bass, Future, Bass, Space',
    title: null,
    description: 'Future Bass, Future, Bass, Space, Nightfall, Slow Motion',
    name: 'Nightfall / Future Bass Music',
    tagLinks:
      '<a href="/music/search/future%20bass/">future bass</a> <a href="/music/search/future/">future</a> <a href="/music/search/bass/">bass</a>',
    likeCount: 25,
    likeHref: '/accounts/like/audio/228100/',
    commentCount: 1,
    commentHref:
      '/music/budouci-basy-nightfall-future-bass-music-228100/#comments',
    contentIdCertificateUrl: '/music/228100/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/soulprodmusic-30064790/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=228100">Oleg Fedak</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=228100">Pixabay</a>',
    vector: false,
    isEditorsChoice: true,
    isLowQuality: false,
    qualityStatus: 5,
    rating: 8.5,
    user: {
      id: 30064790,
      username: 'SoulProdMusic',
      firstName: 'Oleg',
      lastName: 'Fedak',
      avatarSrc:
        'https://cdn.pixabay.com/user/2022/09/20/21-47-25-136_96x96.jpg',
      profileUrl: '/users/soulprodmusic-30064790/',
      socialLinks: [
        {
          url: 'https://www.instagram.com/fedakoleg/',
          type: 2,
        },
        {
          url: 'https://www.youtube.com/c/SoulProdMusic',
          type: 4,
        },
        {
          url: 'https://www.patreon.com/soulprod',
          type: 5,
        },
      ],
      donation: {
        paypal: 'https://www.patreon.com/soulprod',
        method: 1,
      },
      donations: ['https://www.patreon.com/soulprod'],
      followerCount: 2213,
      aboutMe:
        'Hi my name is Oleg. I live and work in Krivoy Rog, Ukraine. My target is to make high-quality music which may become a great background for your projects! Check it out!',
      isAvailableForHire: true,
      isActive: true,
    },
    viewCount: 3311,
    downloadCount: 180,
  },
  {
    id: 211881,
    duration: 131,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/05/24/audio_46382ae035.mp3',
      waveformUrl: '/music/211881/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/05/24/15-24-57-666_200x200.png',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-211881.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: false,
    uploadDate: '2024-08-01T17:26:10.972308',
    href: '/music/flow-211881/',
    alt: 'Elegant, Emotional, Erotic, Fashion Show',
    title: null,
    description: 'Elegant, Emotional, Erotic, Fashion Show, Intro, Love',
    name: 'Flow',
    tagLinks:
      '<a href="/music/search/elegant/">elegant</a> <a href="/music/search/emotional/">emotional</a>',
    likeCount: 739,
    likeHref: '/accounts/like/audio/211881/',
    commentCount: 9,
    commentHref: '/music/flow-211881/#comments',
    contentIdCertificateUrl: null,
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/loksii-40853646/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=211881">Oleksii Holubiev</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=211881">Pixabay</a>',
    vector: false,
    isEditorsChoice: true,
    isLowQuality: false,
    qualityStatus: 5,
    rating: 8,
    user: {
      id: 40853646,
      username: 'Loksii',
      firstName: 'Oleksii',
      lastName: 'Holubiev',
      avatarSrc:
        'https://cdn.pixabay.com/user/2023/11/23/14-24-50-280_96x96.jpg',
      profileUrl: '/users/loksii-40853646/',
      socialLinks: [
        {
          url: 'https://instagram.com/dj.loksii?igshid=NzZlODBkYWE4Ng==',
          type: 2,
        },
        {
          url: 'https://www.youtube.com/@loksii9',
          type: 4,
        },
        {
          url: 'https://open.spotify.com/artist/1BvK52H33IvynANMkz86U5?si=SzgUWKLlSDy_nhoP_sRPdA',
          type: 5,
        },
      ],
      donation: {
        paypal: 'saloid007@gmail.com',
        method: 2,
      },
      donations: ['saloid007@gmail.com'],
      followerCount: 162,
      aboutMe:
        'Music will say more than I can say about myself. I invite you to actively use music in your works, videos, and projects. If you have any questions, please contact me in a message.',
      isAvailableForHire: true,
      isActive: true,
    },
    viewCount: 678893,
    downloadCount: 5172,
  },
  {
    id: 186374,
    duration: 90,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/01/16/audio_e2b992254f.mp3',
      waveformUrl: '/music/186374/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/01/29/13-19-29-218_200x200.png',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-186374.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.972974',
    href: '/music/beats-better-day-186374/',
    alt: 'Better Day is relaxing Chill-Hop track perfect for modern dreamy commercials, promo videos and other media projects.',
    title: null,
    description: 'Aerial, Ambient, Atmospheric, Beat, Chill Beat, Chill-Hop',
    name: 'Better Day',
    tagLinks:
      '<a href="/music/search/aerial/">aerial</a> <a href="/music/search/ambient/">ambient</a>',
    likeCount: 2489,
    likeHref: '/accounts/like/audio/186374/',
    commentCount: 1,
    commentHref: '/music/beats-better-day-186374/#comments',
    contentIdCertificateUrl: '/music/186374/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/penguinmusic-24940186/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=186374">Oleksandr Stepanov</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=186374">Pixabay</a>',
    vector: false,
    isEditorsChoice: true,
    isLowQuality: false,
    qualityStatus: 5,
    rating: 8.5,
    user: {
      id: 24940186,
      username: 'penguinmusic',
      firstName: 'Oleksandr',
      lastName: 'Stepanov',
      avatarSrc:
        'https://cdn.pixabay.com/user/2024/05/28/21-34-22-134_96x96.jpeg',
      profileUrl: '/users/penguinmusic-24940186/',
      socialLinks: [
        {
          url: 'https://youtube.com/channel/UCWXSa_zo49mPGMPs1Pt3dAg',
          type: 4,
        },
        {
          url: 'https://1.envato.market/yXPqy',
          type: 5,
        },
      ],
      donation: {
        paypal: 'creo.musick@gmail.com',
        method: 2,
      },
      donations: ['creo.musick@gmail.com'],
      followerCount: 1532,
      aboutMe:
        'music producer/composer and sound designer\r\n!!! Please send me link to your YouTube video and I will release copyright claim!!!\r\n\r\nYou can support me by adding credits in your video description - “music by penguinmusic - *track title* from Pixabay”\r\n\r\nLike & subscribe',
      isAvailableForHire: true,
      isActive: true,
    },
    viewCount: 2438881,
    downloadCount: 19118,
  },
  {
    id: 226817,
    duration: 138,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/07/24/audio_e449d10473.mp3',
      waveformUrl: '/music/226817/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/07/24/18-10-11-682_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-226817.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.973632',
    href: '/music/beats-alone-in-the-dark-background-hip-hop-music-for-video-full-version-226817/',
    alt: 'Background, Background Music',
    title: null,
    description: 'Background, Background Music, Music For Video',
    name: 'Alone in the dark. Background Hip-Hop music for video. Full version',
    tagLinks: '<a href="/music/search/background/">background</a>',
    likeCount: 111,
    likeHref: '/accounts/like/audio/226817/',
    commentCount: 1,
    commentHref:
      '/music/beats-alone-in-the-dark-background-hip-hop-music-for-video-full-version-226817/#comments',
    contentIdCertificateUrl: '/music/226817/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/white_records-32584949/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=226817">Maksym Dudchyk</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=226817">Pixabay</a>',
    vector: false,
    isEditorsChoice: false,
    isLowQuality: true,
    qualityStatus: 5,
    rating: 7,
    user: {
      id: 32584949,
      username: 'White_Records',
      firstName: 'Maksym',
      lastName: 'Dudchyk',
      avatarSrc:
        'https://cdn.pixabay.com/user/2023/07/22/15-50-31-85_96x96.png',
      profileUrl: '/users/white_records-32584949/',
      socialLinks: [
        {
          url: 'https://facebook.com/profile.php?id=100038573046142',
          type: 0,
        },
        {
          url: 'https://instagram.com/white_recordsmd/',
          type: 2,
        },
        {
          url: 'https://soundcloud.com/whiterecords1',
          type: 3,
        },
        {
          url: 'https://youtube.com/channel/UCi5cB6kg5ZDNtZQ8SawRUvg',
          type: 4,
        },
        {
          url: 'https://buymeacoffee.com/dmdproduction/extras',
          type: 5,
        },
      ],
      donation: {
        paypal: 'https://buymeacoffee.com/dmdproduction',
        method: 1,
      },
      donations: ['https://buymeacoffee.com/dmdproduction'],
      followerCount: 1588,
      aboutMe:
        '📌 Music licenses https://bit.ly/3w9Qy6k\r\nSupport with a donation 💜 https://www.buymeacoffee.com/dmdproduction\r\n📌 My PayPal dmdproductiondmd@gmail.com\r\nHere, we will be publishing instrumental beats and other music for your listening pleasure. Our channel is dedicated to providing you with high-quality, original content that is perfect for studying, working, relaxing, or just vibing out.',
      isAvailableForHire: false,
      isActive: true,
    },
    viewCount: 15544,
    downloadCount: 111,
  },
  {
    id: 200697,
    duration: 155,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/04/07/audio_7917e14f03.mp3',
      waveformUrl: '/music/200697/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/04/07/12-31-59-477_200x200.jpg',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-200697.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.974274',
    href: '/music/upbeat-movement-200697/',
    alt: 'Breakbeat, Car, Promo, Vlog, Action',
    title: null,
    description: 'Breakbeat, Car, Promo, Vlog, Action, Energy, Presentation',
    name: 'Movement',
    tagLinks:
      '<a href="/music/search/breakbeat/">breakbeat</a> <a href="/music/search/car/">car</a> <a href="/music/search/promo/">promo</a>',
    likeCount: 1212,
    likeHref: '/accounts/like/audio/200697/',
    commentCount: 14,
    commentHref: '/music/upbeat-movement-200697/#comments',
    contentIdCertificateUrl: '/music/200697/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/soulprodmusic-30064790/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=200697">Oleg Fedak</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=200697">Pixabay</a>',
    vector: false,
    isEditorsChoice: true,
    isLowQuality: false,
    qualityStatus: 5,
    rating: 8.5,
    user: {
      id: 30064790,
      username: 'SoulProdMusic',
      firstName: 'Oleg',
      lastName: 'Fedak',
      avatarSrc:
        'https://cdn.pixabay.com/user/2022/09/20/21-47-25-136_96x96.jpg',
      profileUrl: '/users/soulprodmusic-30064790/',
      socialLinks: [
        {
          url: 'https://www.instagram.com/fedakoleg/',
          type: 2,
        },
        {
          url: 'https://www.youtube.com/c/SoulProdMusic',
          type: 4,
        },
        {
          url: 'https://www.patreon.com/soulprod',
          type: 5,
        },
      ],
      donation: {
        paypal: 'https://www.patreon.com/soulprod',
        method: 1,
      },
      donations: ['https://www.patreon.com/soulprod'],
      followerCount: 2213,
      aboutMe:
        'Hi my name is Oleg. I live and work in Krivoy Rog, Ukraine. My target is to make high-quality music which may become a great background for your projects! Check it out!',
      isAvailableForHire: true,
      isActive: true,
    },
    viewCount: 1250425,
    downloadCount: 8914,
  },
  {
    id: 191271,
    duration: 440,
    mediaType: 'audio',
    mediaSubType: 3,
    mediaDescriptiveType: 'music',
    sources: {
      src: 'https://cdn.pixabay.com/audio/2024/02/14/audio_b9bc3934cc.mp3',
      waveformUrl: '/music/191271/waveform.json',
      thumbnailUrl:
        'https://cdn.pixabay.com/audio/2024/02/14/22-35-32-207_200x200.png',
      thumbnailOrientation: 'portrait',
      downloadUrl: '/music/download/id-191271.mp3',
    },
    nsfw: false,
    isAiGenerated: false,
    hasYoutubeContentId: true,
    uploadDate: '2024-08-01T17:26:10.974922',
    href: '/music/pulses-perfect-beauty-191271/',
    alt: 'Relax, Spa, Meditation, Nature, Space',
    title: null,
    description: 'Relax, Spa, Meditation, Nature, Space, Sea, Waves, Landscape',
    name: 'Perfect Beauty',
    tagLinks:
      '<a href="/music/search/relax/">relax</a> <a href="/music/search/spa/">spa</a> <a href="/music/search/meditation/">meditation</a>',
    likeCount: 1895,
    likeHref: '/accounts/like/audio/191271/',
    commentCount: 0,
    commentHref: '/music/pulses-perfect-beauty-191271/#comments',
    contentIdCertificateUrl: '/music/191271/license/',
    attributionHtml:
      'Music by <a href="https://pixabay.com/users/good_b_music-22836301/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=191271">Zakhar Valaha</a> from <a href="https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=191271">Pixabay</a>',
    vector: false,
    isEditorsChoice: true,
    isLowQuality: false,
    qualityStatus: 5,
    rating: 9,
    user: {
      id: 22836301,
      username: 'Good_B_Music',
      firstName: 'Zakhar',
      lastName: 'Valaha',
      avatarSrc:
        'https://cdn.pixabay.com/user/2021/11/15/21-52-29-99_96x96.png',
      profileUrl: '/users/good_b_music-22836301/',
      socialLinks: [
        {
          url: 'https://soundcloud.com/goodbmusic-zakhar-valaha?utm_source=clipboard&amp;amp;amp;utm_medium=text&amp;amp;amp;utm_campaign=social_sharing',
          type: 3,
        },
        {
          url: 'https://audiojungle.net/user/goodbmusic',
          type: 5,
        },
      ],
      donation: {
        paypal: 'valaga83@gmail.com',
        method: 2,
      },
      donations: ['valaga83@gmail.com'],
      followerCount: 4805,
      aboutMe: '',
      isAvailableForHire: true,
      isActive: true,
    },
    viewCount: 1950012,
    downloadCount: 17388,
  },
]

export const getMusics = async () => results
